---
# This file is used to configure the project metadata
fullname: rocq-candy
# NOTE: The "shortname" is also the presumed name of the REPOSITORY this lives in!!!
shortname: rocq-candy
lib_name: RocqCandy
opam_name: rocq-candy # i.e. coq-Base64
synopsis: "Snippets of nice and useful Rocq code utilized by the KU-SLDG Lab"
description: "This library contains snippets of nice and useful Rocq code utilized by the KU-SLDG Lab. It is not intended to be a full-fledged library, but rather a collection of useful code that can be shared between projects."
authors:
  - name: "Will Thomas"
    email: "30wthomas@ku.edu"
opam-file-maintainer: "30wthomas@ku.edu" # Need a strong default here or we will accidentally email a Coq developer
opam-file-version: "0.2.2"

######################################################
# NOTE: Optional Extra Info
######################################################
# categories:
#   - name: "<Category>"

# keywords:
#   - name: "<Keyword1>"
#   - name: "<Keyword2>"
dependencies:
ci_extra_repos:
  - description: "KU-SLDG Packages"
    name: "ku-sldg/opam-repo"
    url: "https://github.com/ku-sldg/opam-repo.git"

coq_trans_deps_workaround: true

######################################################
# NOTE: Stuff below this line you should not need to change
# other than on occassion the `config options`
######################################################
# NOTE: check out https://github.com/coq-community/templates/blob/master/ref.yml for more possible values

branch: main
organization: ku-sldg

# Config Options
community: false # By default projects are not part of coq-community
coqdoc: false # By default we want coqdoc
submodule: false # By default we don't want submodules
dune: true # By default we want dune builds
ocaml_plugin: false # By default we don't assume plugins to use ocaml code
# date: # by default we arent setting a date

# CI services - we only want GH Actions by default
# NOTE: You should not need to change these usually!
travis: false
action: true
circleci: false
nix: false
ci_test_dependants: false
ci_extra_dev: false
ci_cron_schedule: 0 0 * * 0 # Weekly at midnight sunday
tested_rocq_opam_versions:
  - version: "9.0"
  # - version: "9.0"
  #   repo: "rocq/rocq-prover"

## UNKNOWN: action_appendix:

# Extra Metadata
# doi:
# chat: # if we ever have a chat room?
license:
  - fullname: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0
    file: LICENSE
supported_coq_versions:
  - text: "8.20 later"
    opam: '{ >= "8.20~" }'
supported_ocaml_versions:
  - text: "4.12 or later"
    opam: '{ >= "4.12~" }'
